### ISSUE TITLE
GRUNTWORK_PHILOSOPHY.md table GCP examples

### ISSUE THREAD

**Issue by autero1** [gruntwork-io/terraform-google-sql#27]
All of the examples in https://github.com/gruntwork-io/terraform-google-sql/blob/master/GRUNTWORK_PHILOSOPHY.md of cloud provider resources are AWS-based; once we have support for some GCP resources/modules, let's update the version of GRUNTWORK_PHILOSOPHY.md in this repo to include their GCP equivalents.

https://github.com/gruntwork-io/terraform-google-gke/issues/4

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-sql#sunset-notice)
