### ISSUE TITLE
PostgreSQL module is not idempotent

### ISSUE THREAD

**Issue by rgreinho** [gruntwork-io/terraform-google-sql#46]
Every time the module is run, Terraform shows this message and acts as if there are changes to apply:

```HCL
Terraform will perform the following actions:

  # module.commerce_db_staging.data.template_file.complete will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "complete"  {
      + id       = (known after apply)
      + rendered = (known after apply)
      + template = "true"
    }
```

**Comment by hamann** [comment]
@rgreinho Did you find a solution for this?

**Comment by jsirianni** [comment]
I have been dealing with this as well. I have learned to just ignore it, probably not the best solution.

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-sql#sunset-notice)
