### ISSUE TITLE
How do I set credentials?

### ISSUE THREAD

**Issue by newtoniumx3** [gruntwork-io/terraform-google-sql#48]
I'm using GCP and the only way I found to use my credentials file right now was to export environment variable.

```sh
export GOOGLE_APPLICATION_CREDENTIALS="../credentials.json"
```

I would previously define this within the provider like so:
```sh
provider "google" {
  project     = "test"
  region      = "us-central1-a"
  credentials = file("../secrets.json")
}
```

But when I add this credentials key to the provider (within main.tf) I  get
```sh
Error: Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'.  Original error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by robmorgan** [comment]
Hi @newtoniumx3 ,

The recommended approach is to set your [GCP credentials using the environment variable you've specified](https://www.terraform.io/docs/providers/google/guides/getting_started.html#adding-credentials). You can also use the `provider` blocks, but you'll need to make sure you set the `credentials` key and ensure its in the correct format for all `google` and `google-beta` provider blocks.

**Comment by newtoniumx3** [comment]
Thank you!
