### ISSUE TITLE
Mysql 8 HA error: ERROR_DISALLOW_FAILOVER_REPLICA_WHEN_DISABLED

### ISSUE THREAD

**Issue by theFong** [gruntwork-io/terraform-google-sql#54]
Hello,

When deploying Cloud SQL with Mysql 8, the HA/failover setup does not work. I have confirmed on my end that only changing the mysql version causes this issue. I have a work around here https://github.com/theFong/terraform-google-sql. Let me know if it would make a good PR and I can do so.

```
Error 400: Request contains an invalid argument.
More details:
Reason: ERROR_DISALLOW_FAILOVER_REPLICA_WHEN_DISABLED, Message:
```

**Comment by robmorgan** [comment]
@theFong  Hey Alec,

Yes please open a PR and we can add a test around it to see if it fixes it!

Regards,

Rob

**Comment by SteveGoodenough** [comment]
Any movement on this?, I've run into same issue when migrating a user from mysql 5.7 to 8.0; same terraform, just the version change.

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-sql#sunset-notice)
