### ISSUE TITLE
Add `encryption_key_name` for encryption at rest

### ISSUE THREAD

**Issue by olmesm** [gruntwork-io/terraform-google-sql#71]
As per current GCP Provider docs, `google_sql_database_instance` allows for encryption at rest if an encryption key address is supplied.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#encryption_key_name

Fix: https://github.com/gruntwork-io/terraform-google-sql/pull/72

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-sql#sunset-notice)
