### ISSUE TITLE
Expose settings.backup_configuration.backup_retention_settings.retained_backups

### ISSUE THREAD

**Issue by aleccool213** [gruntwork-io/terraform-google-sql#81]
**Describe the solution you'd like**

I would like to access this setting to increase my retained backup count from the default of 7 days to 90 days.

**Describe alternatives you've considered**

Not accessible so I cannot use the module.

**Additional context**

Link to resource docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#retained_backups

Screenshot:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/6475934/202793229-37915aef-ca84-45e9-b758-fb86d3019524.png">

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-sql#sunset-notice)
